#include "sim_mem.h"
#include <iostream>
char main_memory[MEMORY_SIZE];
using namespace std;

int main(){
    char exe1[20] = "exec_file.txt";
    char exe2[20] = "exec_file2";
    char swap[20] = "swap_file.txt";
    sim_mem mem_sim(exe1,exe2,swap,25,50,25,25,
                    25,5,2);
    mem_sim.store(1,25,'A');
    mem_sim.store(1,26,'B');
    mem_sim.store(1,27,'C');
    mem_sim.store(1,28,'D');
    mem_sim.store(1,29,'E');
    mem_sim.store(1,30,'F');
    mem_sim.store(1,31,'G');
    mem_sim.store(1,32,'H');
    mem_sim.store(1,33,'I');
    mem_sim.store(1,34,'J');
    mem_sim.store(1,35,'K');
    mem_sim.store(1,36,'L');
    mem_sim.store(1,37,'M');
    mem_sim.store(1,38,'N');
    mem_sim.store(1,39,'O');
    mem_sim.store(1,40,'P');
    mem_sim.store(1,41,'Q');
    mem_sim.store(1,42,'R');
    mem_sim.store(1,43,'S');
    mem_sim.store(1,44,'T');
    mem_sim.store(1,45,'U');
    mem_sim.store(1,46,'V');
    mem_sim.store(1,47,'W');
    mem_sim.store(1,48,'X');
    mem_sim.store(1,49,'Y');
    mem_sim.store(1,50,'Z');
    cout<< "PAGE 1 : "<< mem_sim.load(1,25);
    cout<< mem_sim.load(1,26);
    cout<< mem_sim.load(1,27);
    cout<< mem_sim.load(1,28);
    cout<< mem_sim.load(1,29)<<endl;
    cout<< "PAGE 2 : "<< mem_sim.load(1,30);
    cout<< mem_sim.load(1,31);
    cout<< mem_sim.load(1,32);
    cout<< mem_sim.load(1,33);
    cout<< mem_sim.load(1,34)<<endl;
    cout<< "PAGE 3 : "<< mem_sim.load(1,35);
    cout<< mem_sim.load(1,36);
    cout<< mem_sim.load(1,37);
    cout<< mem_sim.load(1,38);
    cout<< mem_sim.load(1,39)<<endl;
    cout<< "PAGE 4 : "<< mem_sim.load(1,40);
    cout<< mem_sim.load(1,41);
    cout<< mem_sim.load(1,42);
    cout<< mem_sim.load(1,43);
    cout<< mem_sim.load(1,44)<<endl;
    cout<< "PAGE 5 : "<< mem_sim.load(1,45);
    cout<< mem_sim.load(1,46);
    cout<< mem_sim.load(1,47);
    cout<< mem_sim.load(1,48);
    cout<< mem_sim.load(1,49)<<endl;
    cout<< "PAGE 6 : "<< mem_sim.load(1,75);
    cout<< mem_sim.load(1,76);
    cout<< mem_sim.load(1,77);
    cout<< mem_sim.load(1,78);
    cout<< mem_sim.load(1,79)<<endl;
    mem_sim.store(2,55,'B');
    mem_sim.store(2,56,'Y');
    mem_sim.store(2,57,'E');
    mem_sim.store(2,58,'!');
    mem_sim.store(2,59,'!');
    cout<< "Last Page : " << mem_sim.load(2,55);
    cout << mem_sim.load(2,56);
    cout << mem_sim.load(2,57);
    cout << mem_sim.load(2,58);
    cout << mem_sim.load(2,59)<<endl;
//     THESE TEST FOR MY EXE FILES
//    cout<<"Name :";
//    cout<<mem_sim.load(1,5);
//    cout<<mem_sim.load(1,6);
//    cout<<mem_sim.load(1,7);
//    cout<<mem_sim.load(1,8);
//    cout<<mem_sim.load(1,9);
//    cout<<" ";
//    cout<<mem_sim.load(1,10);
//    cout<<mem_sim.load(1,11);
//    cout<<mem_sim.load(1,12);
//    cout<<" ";
//    cout<<mem_sim.load(1,13);
//    cout<<mem_sim.load(1,14);
//    cout<<mem_sim.load(1,15);
//    cout<<mem_sim.load(1,16);
//    cout<<mem_sim.load(1,17);
//    cout<<mem_sim.load(1,18);
//    cout<<mem_sim.load(1,19);
//    cout<<mem_sim.load(1,20)<<endl;
//    cout<<"ID :";
//    cout<<mem_sim.load(2,3);
//    cout<<mem_sim.load(2,4);
//    cout<<mem_sim.load(2,5);
//    cout<<mem_sim.load(2,6);
//    cout<<mem_sim.load(2,7);
//    cout<<mem_sim.load(2,8);
//    cout<<mem_sim.load(2,9);
//    cout<<mem_sim.load(2,10);
//    cout<<mem_sim.load(2,11);

    mem_sim.print_memory();
    mem_sim.print_swap();
    mem_sim.print_page_table();
}